production:
  adapter: redis
  url: redis://localhost:6379/1

development:
  adapter: redis
  url: redis://localhost:6379/1

staging:
  adapter: redis
  url: redis://localhost:6379/1

test:
  adapter: async